version: "3"
services:
  db:
    container_name: song-service-db
    image: postgres:15
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: w1lly_w0nka
      POSTGRES_PASSWORD: ch0kolate_f@ctory
      POSTGRES_DB: songs